### ISSUE TITLE
Alloy support

### ISSUE THREAD

**Issue by ottopic** [lambus-platform/titanium-notification-banner#2]
`ReferenceError: buildAlloy is not defined
    at /Users/user/Documents/GitHub/app/modules/iphone/ti.notificationbanner/2.0.0/hooks/ti.swiftsupport.js:26:54
    at Array.forEach (<anonymous>)
    at /Users/user/Documents/GitHub/app/modules/iphone/ti.notificationbanner/2.0.0/hooks/ti.swiftsupport.js:25:83
    at Array.forEach (<anonymous>)
    at iOSBuilder.pre (/Users/user/Documents/GitHub/app/modules/iphone/ti.notificationbanner/2.0.0/hooks/ti.swiftsupport.js:22:39)
    at /Users/user/.appcelerator/install/7.1.2/package/node_modules/titanium/lib/hook.js:223:10
    at /Users/user/.appcelerator/install/7.1.2/package/node_modules/titanium/node_modules/async/dist/async.js:3880:24
    at replenish (/Users/user/.appcelerator/install/7.1.2/package/node_modules/titanium/node_modules/async/dist/async.js:1011:17)
    at /Users/user/.appcelerator/install/7.1.2/package/node_modules/titanium/node_modules/async/dist/async.js:1016:9
    at eachOfLimit (/Users/user/.appcelerator/install/7.1.2/package/node_modules/titanium/node_modules/async/dist/async.js:1041:24)`

**Comment by hansemannn** [comment]
This is not module related. We use it in an Alloy app without issues

**Comment by ottopic** [comment]
@hansemannn how do you import it? 
It's my first Alloy app, but with other modules I have not this problem. 
I have /modules/iphone/ti.notificationbanner/2.0.0/ and import it with 

`import NotificationBanner from 'ti.notificationbanner';`

inside Alloy.js. Is this true?
